version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
            
jobs:
  validate-app:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name : Validate app content
          command: |
            sudo npm i html-validator-cli -g
            sudo html-validator --file=src/index.html
  
  scan-dockerfile:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: install hadolint
          command: |
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x ./hadolint
      - run:
          name: lint Dockerfile
          command: |
            ./hadolint Dockerfile
  
  build-docker:
    docker:
      - image: cimg/node:16.15.1
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - docker/check
      - docker/build:
          image: udacity-capstone-project
          registry: 'vuachicken6'
          tag: "${CIRCLE_WORKFLOW_ID:0:7}"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: udacity-capstone-project
          registry: 'vuachicken6'
          tag: "${CIRCLE_WORKFLOW_ID:0:7}"
      - docker/push:
          image: udacity-capstone-project
          registry: 'vuachicken6'
          tag: "latest"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    docker:
      - image: cimg/python:3.10.6
    parameters:
      cluster-name:
        description: |
          Udacity Capstone Cluster Name
        type: string
    steps:
      - checkout
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          node-type: "t3.large"
          show-eksctl-command : true
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - kubernetes/create-or-update-resource:
          resource-file-path: ".circleci/files/deployment.yml"
          show-kubectl-command: true
          resource-name: "deployment/udacity-capstone-project"
      - run:
          name: Log status
          command: |
            kubectl get services
            kubectl get deployment
            kubectl get nodes
            kubectl get pods --all-namespaces
workflows:
  default:
    jobs:
      - validate-app
      - scan-dockerfile:
          requires: [validate-app]
      - build-docker:
          requires: [scan-dockerfile]
      - deploy:
          cluster-name: 'udacity-capstone-project'
          requires: [build-docker]